REM save current directory
set startingDirectory=%CD%

REM Build release version of DataFiles project
CALL compileReleaseProjects.bat

REM Build Nuget package
nuget pack WithoutHaste.DataFiles.nuspec
REM Sign NuGet package
nuget sign WithoutHaste.DataFiles.1.0.0-alpha2.nupkg -CertificatePath E:\Adulting\WithoutHasteLLC\Certificates\Comodo_certificate_backup_PKCS12_from_firefox.p12 -Timestamper http://sha256timestamp.ws.symantec.com/sha256/timestamp

REM Copy package to local test source folder
xcopy *.nupkg ..\..\..\NuGetTestSource

REM Run InstallationTestsSetup
cd ..\InstallationTests
START /WAIT Setup\InstallationTestsSetup\bin\Release\InstallationTestsSetup.exe

REM Install NuGet package in each auto-generated solution
set installationTestsDirectory=%CD%
set frameworks=20 30 35 40 45 451 452 46 461 462 47 471 472
(for %%f in (%frameworks%) do ( 
	cd %installationTestsDirectory%
	cd AutoGenerated\net%%f
 	nuget install-package WithoutHaste.DataFiles -Version 1.0.0-alpha2
))
 
REM Return to starting directory
cd %startingDirectory%