REM Because you cannot unload a loaded assembly without putting it into its own AppDomain...
REM just running this individually for each dll
bin\Debug\BuildVerification.exe "..\DataFiles\bin\Debug\net20\WithoutHaste.DataFiles.dll"
bin\Debug\BuildVerification.exe "..\DataFiles\bin\Debug\net30\WithoutHaste.DataFiles.dll"
bin\Debug\BuildVerification.exe "..\DataFiles\bin\Debug\net35\WithoutHaste.DataFiles.dll"
bin\Debug\BuildVerification.exe "..\DataFiles\bin\Debug\net40\WithoutHaste.DataFiles.dll"
bin\Debug\BuildVerification.exe "..\DataFiles\bin\Debug\net45\WithoutHaste.DataFiles.dll"
bin\Debug\BuildVerification.exe "..\DataFiles\bin\Debug\net451\WithoutHaste.DataFiles.dll"
bin\Debug\BuildVerification.exe "..\DataFiles\bin\Debug\net452\WithoutHaste.DataFiles.dll"
bin\Debug\BuildVerification.exe "..\DataFiles\bin\Debug\net46\WithoutHaste.DataFiles.dll"
bin\Debug\BuildVerification.exe "..\DataFiles\bin\Debug\net461\WithoutHaste.DataFiles.dll"
bin\Debug\BuildVerification.exe "..\DataFiles\bin\Debug\net462\WithoutHaste.DataFiles.dll"
bin\Debug\BuildVerification.exe "..\DataFiles\bin\Debug\net47\WithoutHaste.DataFiles.dll"
bin\Debug\BuildVerification.exe "..\DataFiles\bin\Debug\net471\WithoutHaste.DataFiles.dll"
bin\Debug\BuildVerification.exe "..\DataFiles\bin\Debug\net472\WithoutHaste.DataFiles.dll"

bin\Debug\BuildVerification.exe "..\DataFiles\bin\Release\net20\WithoutHaste.DataFiles.dll"
bin\Debug\BuildVerification.exe "..\DataFiles\bin\Release\net30\WithoutHaste.DataFiles.dll"
bin\Debug\BuildVerification.exe "..\DataFiles\bin\Release\net35\WithoutHaste.DataFiles.dll"
bin\Debug\BuildVerification.exe "..\DataFiles\bin\Release\net40\WithoutHaste.DataFiles.dll"
bin\Debug\BuildVerification.exe "..\DataFiles\bin\Release\net45\WithoutHaste.DataFiles.dll"
bin\Debug\BuildVerification.exe "..\DataFiles\bin\Release\net451\WithoutHaste.DataFiles.dll"
bin\Debug\BuildVerification.exe "..\DataFiles\bin\Release\net452\WithoutHaste.DataFiles.dll"
bin\Debug\BuildVerification.exe "..\DataFiles\bin\Release\net46\WithoutHaste.DataFiles.dll"
bin\Debug\BuildVerification.exe "..\DataFiles\bin\Release\net461\WithoutHaste.DataFiles.dll"
bin\Debug\BuildVerification.exe "..\DataFiles\bin\Release\net462\WithoutHaste.DataFiles.dll"
bin\Debug\BuildVerification.exe "..\DataFiles\bin\Release\net47\WithoutHaste.DataFiles.dll"
bin\Debug\BuildVerification.exe "..\DataFiles\bin\Release\net471\WithoutHaste.DataFiles.dll"
bin\Debug\BuildVerification.exe "..\DataFiles\bin\Release\net472\WithoutHaste.DataFiles.dll"
